services:
  - type: web
    name: economic-dashboard-api
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: DOMAIN_CLIENT_ID
        value: "client_991dfcf61ca75ac09f95ef73a7807596"
      - key: DOMAIN_CLIENT_SECRET
        value: "secret_e8b49ae07c05eb3c366a438efa0c91f8"
      - key: NEWSDATA_KEY
        sync: false
      - key: NEWSAPI_KEY
        sync: false
